//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarpScheduling.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarpScheduling.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT p.Warp_MO, p.Expr1, Sum(p.Tickets) TotalRolls, Min(p.DueDate) FROM manufacturing.`plan log` p
        ///Where p.WarpProcessed =0 and p.duedate is not null and p.duedate Not Like &apos;0001-01-01%&apos;
        ///Group by p.Warp_MO, p.Expr1 
        ///Order by Warp_MO;.
        /// </summary>
        internal static string NewWarps {
            get {
                return ResourceManager.GetString("NewWarps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a.ItemNumber, a.ComponentItemNumber, ii.ItemDescription, RequiredQuantity From  (Select i.ItemNumber, i.ItemDescription, i.ItemKey, b.ComponentItemNumber , b.ComponentItemKey, b.RequiredQuantity
        ///From dbo.FS_Item i  Inner Join dbo.FS_BillOfMaterial b on i.ItemKey=b.ParentItemKey
        ///Where i.ItemNumber Like &apos;WS%&apos; and i.ItemStatus &lt;&gt;&apos;O&apos; ) a Inner Join dbo.FS_Item ii on a.ComponentItemKey=ii.ItemKey
        ///Where RequiredQuantity&gt;.009 
        ///Group by a.ItemNumber, a.ComponentItemNumber, ii.ItemDescription, RequiredQua [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WBIll {
            get {
                return ResourceManager.GetString("WBIll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Warp_MO,Customer, Item, Sum(Tickets) Ticket From
        ///manufacturing.`Plan Log`
        ///Where DueDate&gt; AddDate(CurDate(),Interval -180 Day)
        ///Group by Warp_MO, Customer, Item.
        /// </summary>
        internal static string WpMOCustomer {
            get {
                return ResourceManager.GetString("WpMOCustomer", resourceCulture);
            }
        }
    }
}
